---
# Basic provisioning example
- name: Create AWS resources
  hosts: localhost
  connection: local
  vars_files:
    - ../host_vars/var.yml
    - ../host_vars/vault.yml
  gather_facts: False

# Single instance with standard root volume
  tasks:
  - name: Create an EC2 instance
    ec2:
     key_name: Linux01
     group: ansible
     instance_type: t2.micro
     image: ami-013be31976ca2c322
     region: "{{aws_region}}"
     aws_access_key: "{{aws_access_key}}"
     aws_secret_key: "{{aws_secret_key}}"
     count: 1
     wait: yes
     wait_timeout: 500
     volumes:
       - device_name: /dev/xvda
         volume_type: standard
         volume_size: 8
     vpc_subnet_id: subnet-a5aa3cc2
     assign_public_ip: no
     instance_tags:
       Name: AnsibleTestserver
       CostCenter: MyCost






