---
# Basic provisioning example
- name: Create AWS resources
  hosts: localhost
  connection: local
  vars_files:
    - ../host_vars/var.yml
    - ../host_vars/vault.yml
  gather_facts: False
  tasks:
  - name: Create a security group
    ec2_group:
      name: ansible
      description: "Ansible Security Group"
      region:  us-east-1
      vpc_id: vpc-cad173b0
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"          
      rules:
        - proto: all
          cidr_ip: 14.140.150.250/32
        - proto: all
          group_name: ansible
      rules_egress:
        - proto: all
          cidr_ip: "0.0.0.0/0"
    register: firewall
