
- name: Terminate instances
  hosts: localhost
  connection: local
  vars_files:
    - ../host_vars/var.yml
    - ../host_vars/vault.yml
  gather_facts: False

  tasks:
  - name: Terminate instances that were previously launched
    ec2:
     aws_access_key: "{{aws_access_key}}"
     aws_secret_key: "{{aws_secret_key}}"
     region:  "{{aws_region}}"
     state: 'absent'
     instance_ids: 
         - i-05578e8f908950440


